tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

brew "tmux"
brew "stow"
brew "neovim"

cask "appcleaner"
cask "discord"
cask "brave-browser"
cask "spotify"
cask "sublime-text"
cask "vlc"
cask "iterm2"
cask "font-hack-nerd-font"
