tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "gnu-time"
brew "stow"

cask "font-hack"

cask "appcleaner"
cask "discord"
cask "gcc"
cask "google-chrome"
cask "iterm2"
cask "spotify"
cask "sublime-text"
cask "vlc"

