tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "gcc"
brew "gnu-time"
brew "stow"
brew "neovim"

cask "font-hack"

cask "appcleaner"
cask "discord"
cask "brave-browser"
cask "iterm2"
cask "spotify"
cask "sublime-text"
cask "vlc"
cask "notion"

