tap "homebrew/bundle"

brew "antidote"
brew "fzf"
brew "gnu-sed"
brew "go"
brew "lazygit"
brew "node"
brew "nvm"
brew "nvim"
brew "orbstack"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "zoxide"

cask "citrix-workspace"
cask "fantastical"
cask "ghostty"
cask "nikitabobko/tap/aerospace"
cask "thebrowsercompany-dia"
cask "todoist-app"
cask "obsidian"
cask "zed"
cask "zoom"
